version: '3.8'

services:
  simit-checker:
    # Construye la imagen usando el Dockerfile en el directorio actual.
    build: .

    # Define la ruta del directorio de trabajo y el comando a ejecutar.
    # El comando sobrescribe la instrucción CMD en el Dockerfile para
    # pasar la placa del vehículo como argumento.
    command: ["python3", "/app/simit_checker.py", "LKQ163"]

    # Sincroniza el directorio local 'app' con el directorio '/app' del contenedor.
    # Esto es crucial para que cualquier cambio en tu código Python se refleje
    # automáticamente en el contenedor sin necesidad de reconstruir la imagen.
    volumes:
      - ./app:/app