version: '3.7'

services:
  samba:
    image: "dperson/samba:latest"
    environment:
      TZ: America/Bogota
      PGID: 1000
      UGID: 1000
    networks:
      - default
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /var/lib/docker/volumes/qbittorrent_data/AnimeMovies:/AnimeMovies:z
      - /var/lib/docker/volumes/qbittorrent_data/AnimeSeries:/AnimeSeries:y
      - /var/lib/docker/volumes/qbittorrent_data/Marvel:/Marvel:x
      - /var/lib/docker/volumes/qbittorrent_data/Movies:/Movies:w
      - /var/lib/docker/volumes/qbittorrent_data/Series:/Series:v
      - /var/lib/docker/volumes/samba_data/run:/run/samba
      - /var/lib/docker/volumes/samba_data/etc:/etc
      - /var/lib/docker/volumes/samba_data/cache:/var/cache/samba
      - /var/lib/docker/volumes/samba_data/lib:/var/lib/samba
      - /var/lib/docker/volumes/samba_data/log:/var/log/samba
    command: '-s "AnimeMovies;/AnimeMovies;yes;no;no;aslo" \
              -s "AnimeSeries;/AnimeSeries;yes;no;no;aslo" \
              -s "Marvel;/Marvel;yes;no;no;aslo" \
              -s "Movies;/Movies;yes;no;no;aslo" \
              -s "Series;/Series;yes;no;no;aslo" \
              -u "aslo;Andres...1990" -p'

networks:
  default: