version: '3.7'

services:
  samba:
    container_name: samba
    image: "dperson/samba:latest"
    environment:
      TZ: America/Bogota
    networks:
      - default
    ports:
      - 139:139
      - 445:445
    read_only: true
    tmpfs:
      - /tmp
    restart: always
    stdin_open: true
    tty: true
    volumes:
      - /var/lib/docker/volumes/qbittorrent_data/AnimeMovies:/AnimeMovies:z
      - /var/lib/docker/volumes/qbittorrent_data/AnimeSeries:/AnimeSeries:y
      - /var/lib/docker/volumes/qbittorrent_data/Marvel:/Marvel:x
      - /var/lib/docker/volumes/qbittorrent_data/Movies:/Movies:w
      - /var/lib/docker/volumes/qbittorrent_data/Series:/Series:v
      - /var/lib/docker/volumes/samba_data/run:/run/samba
      - /var/lib/docker/volumes/samba_data/etc:/etc
      - /var/lib/docker/volumes/samba_data/cache:/var/cache/samba
      - /var/lib/docker/volumes/samba_data/lib:/var/lib/samba
      - /var/lib/docker/volumes/samba_data/log:/var/log/samba
    command: '-s "AnimeMovies;/AnimeMovies;yes;no;no" \
              -s "AnimeSeries;/AnimeSeries;yes;no;no" \
              -s "Marvel;/Marvel;yes;no;no" \
              -s "Movies;/Movies;yes;no;no" \
              -s "Series;/Series;yes;no;no" \
              -u "ASLO;Andres...1990" -p'

networks:
  default: