version: '3.7'
services:
  samba:
    container_name: samba
    image: "dperson/samba"
    restart: always
    command: '-u "aslo;Andres...1990" -s "AnimeMovies;/AnimeMovies;yes;no"'
    stdin_open: true
    tty: true
    environment:
      TZ: America/Bogota
      PGID: 1000
      UGID: 1000
    network_mode: host
    ports:
      - 139:139
      - 445:445
    volumes:
      - /var/lib/docker/volumes/qbittorrent_data/AnimeMovies:/AnimeMovies
      - /var/lib/docker/volumes/qbittorrent_data/AnimeSeries:/AnimeSeries:y
      - /var/lib/docker/volumes/qbittorrent_data/Marvel:/Marvel:x
      - /var/lib/docker/volumes/qbittorrent_data/Movies:/Movies:w
      - /var/lib/docker/volumes/qbittorrent_data/Series:/Series:v
#       - /var/lib/docker/volumes/samba_data/run:/run/samba
#       - /var/lib/docker/volumes/samba_data/etc:/etc
#       - /var/lib/docker/volumes/samba_data/cache:/var/cache/samba
#       - /var/lib/docker/volumes/samba_data/lib:/var/lib/samba
#       - /var/lib/docker/volumes/samba_data/log:/var/log/samba
