version: '3.7'
services:
  qbittorrent:
    container_name: qbittorrent
    image: "cr.hotio.dev/hotio/qbittorrent"
    restart: always
    environment:
      TZ: America/Bogota
      PGID: 1000
      UGID: 1000
      WEBUI_PORT: 8080
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - /home/docker_data/docker/volumes/qbittorrent_data/config:/config
      - /home/docker_data/docker/volumes/qbittorrent_data/AnimeMovies:/AnimeMovies
      - /home/docker_data/docker/volumes/qbittorrent_data/AnimeSeries:/AnimeSeries
      - /home/docker_data/docker/volumes/qbittorrent_data/DC:/DC
      - /home/docker_data/docker/volumes/qbittorrent_data/Marvel:/Marvel
      - /home/docker_data/docker/volumes/qbittorrent_data/Movies:/Movies
      - /home/docker_data/docker/volumes/qbittorrent_data/Series:/Series
    #network_mode: host
