version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    environment:
      TZ: America/Bogota
      PGID: 1000
      UGID: 1000
      WEBUI_PORT: 8080
    volumes:
       - /var/lib/docker/volumes/prometheus_data/config:/config
       - /var/lib/docker/volumes/prometheus_data/etc/prometheus:/etc/prometheus
    restart: unless-stopped
    networks:
      - prometheus
      
networks:
  prometheus:
    driver: bridge
    name: prometheus