version: '3.7'
services:
  qbittorrent:
    container_name: plex
    image: "jaymoulin/plex:latest"
    restart: unless-stopped
    environment:
      TZ: America/Bogota
      PGID: 1000
      UGID: 1000
    expose:
      - 32400
      - 33400
    volumes:
      - /var/lib/docker/volumes/plex_data/config:/config
      - /var/lib/docker/volumes/plex_data/library:/root/Library
      - /var/lib/docker/volumes/plex_data/media:/media
      - /var/lib/docker/volumes/plex_data/transcode:/transcode
      - /var/lib/docker/volumes/qbittorrent_data/AnimeMovies:/AnimeMovies
      - /var/lib/docker/volumes/qbittorrent_data/AnimeSeries:/AnimeSeries
      - /var/lib/docker/volumes/qbittorrent_data/Marvel:/Marvel
      - /var/lib/docker/volumes/qbittorrent_data/Movies:/Movies
      - /var/lib/docker/volumes/qbittorrent_data/Series:/Series
    network_mode: host