version: "3.9"

services:
  n8n:
    build: ./n8n-custom
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - TZ=America/Bogota
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=Colombia2025*
      - GENERIC_TIMEZONE=America/Bogota
      - N8N_SECURE_COOKIE=false
      - N8N_HOST=n8n.asloos.uk
      - N8N_PROTOCOL=https
      - N8N_WEBHOOK_URL=https://n8n.asloos.uk/
      - WEBHOOK_TUNNEL_URL=https://n8n.asloos.uk/
    user: "1000:1000"
    volumes:
      - /var/lib/docker/volumes/n8n_data:/home/node/.n8n
      - /var/lib/docker/volumes/n8n_files:/home/node/files
