version: "3"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - /var/lib/docker/volumes/prometheus_data/config:/config
      - /var/lib/docker/volumes/prometheus_data/etc/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: unless-stopped