version: "3.7"

services:
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    environment:
      TZ: America/Bogota
      PGID: 1000
      UGID: 1000
    volumes:
      - /var/lib/docker/volumes/prometheus_data/config:/config
      - /var/lib/docker/volumes/prometheus_data/etc/prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    restart: always