version: '3.7'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - /var/lib/docker/volumes/prometheus_data/config:/config
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    restart: unless-stopped
    networks:
      - prometheus
      
networks:
  prometheus:
    driver: bridge
    name: prometheus