version: '3.7'

services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    environment:
      TZ: America/Bogota
      PGID: 1000
      UGID: 1000
    volumes:
      - /var/lib/docker/volumes/homeassistant_data/config:/config
    restart: unless-stopped
    privileged: true
    network_mode: host

  shell_command:
    image: "ubuntu"  # Puedes usar una imagen basada en Alpine si prefieres algo más ligero
    command: >
      /bin/sh -c "curl -o /config/commands.sh https://raw.githubusercontent.com/ASLObit/Docker/main/homeassistant/commands.sh && chmod +x /config/commands.sh"
    volumes:
      - /var/lib/docker/volumes/homeassistant_data/config:/config
    depends_on:
      - homeassistant
    stdin_open: true
    tty: true
