version: '3.7'

services:

  supervisor:
    container_name: homeassistant_supervisor
    image: "homeassistant/amd64-hassio-supervisor"
    volumes:
      - /var/lib/docker/volumes/homeassistant_data/supervisor:/data
    privileged: true
    restart: unless-stopped
    
  homeassistant:
    container_name: homeassistant
    image: "homeassistant/home-assistant:2024.1.0b4"
    environment:
      TZ: America/Bogota
      PGID: 1000
      UGID: 1000
    volumes:
      - /var/lib/docker/volumes/homeassistant_data/config:/config
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - supervisor

# shell_command:
#   image: "alpine"
#   command: >
#     #/bin/sh -c "apk update && apk add curl && curl -o /config/commands.sh https://raw.githubusercontent.com/ASLObit/Docker/main/homeassistant/commands.sh && chmod +x /config/commands.sh && tail -f /dev/null"
#     #/bin/sh -c "apk update && apk add curl && curl -o /config/backup.sh https://raw.githubusercontent.com/ASLObit/Docker/main/homeassistant/backup.sh && chmod +x /config/backup.sh && tail -f /dev/null"
#   volumes:
#     - /var/lib/docker/volumes/homeassistant_data/config:/config
#   depends_on:
#     - homeassistant
#   entrypoint: ["/bin/sh", "-c"]
#   stdin_open: true
#   tty: true

# gdrive:
#   image: alpine:latest
#   volumes:
#     - /var/lib/docker/volumes/homeassistant_data/config:/config
#   command: >
#     #apk update && apk add gdrive && /bin/sh -c "tail -f /dev/null"
