version: "3.8"
services:
  supervisor:
    image: lansible/home-assistant:latest
    volumes:
      - /var/lib/docker/volumes/homeassistant_data/config:/config
      - /tmp:/tmp
    restart: unless-stopped
    privileged: true
    network_mode: host
