version: "3"
# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    restart: unless-stopped
    cap_add:
        - NET_ADMIN
    dns:
      - 127.0.0.1
      - 1.1.1.1
    environment:
      ServerIP: 192.168.20.200
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
      VIRTUAL_HOST: pi.hole
      DNSMASQ_LISTENING: all
    volumes:
      - /var/lib/docker/volumes/pihole_data/etc:/etc/pihole
      - /var/lib/docker/volumes/pihole_data/dnsmasq.d:/etc/dnsmasq.d
    # depends_on:
    #   - dhcphelper
    networks:
      backend:
        ipv4_address: '192.168.20.200'
      frontproxy_proxy-tier: {}

#  dhcphelper:
#    build: ./dhcp-helper
#    restart: unless-stopped
#    network_mode: "host"
#    command: -s 192.168.20.200
#    cap_add:
#      - NET_ADMIN

networks:
  backend:
    ipam:
      config:
        - subnet: 192.168.0.0/16
  frontproxy_proxy-tier:
    external: true


