version: "3.9"

services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - /var/lib/docker/volumes/emulator_data/emulatorjs/config:/config
      - /var/lib/docker/volumes/emulator_data/roms:/data/roms
      - /var/lib/docker/volumes/emulator_data/assets:/data/assets
    ports:
      - "3000:3000"   # panel de administración
      - "8088:80"       # frontend público (jugar)
    restart: unless-stopped
