version: "3.9"

services:
  emulatorjs:
    image: docker.io/linuxserver/emulatorjs:1.9.2
    platform: "linux/amd64"
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Bogota
    volumes:
      - /var/lib/docker/volumes/emulator_data/emulatorjs/config:/config
      - /var/lib/docker/volumes/emulator_data:/data
    ports:
      - "3100:3000"   # panel
      - "8088:80"     # frontend
    restart: unless-stopped
