version: '3.7'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /Docker/traefik/letsencrypt:/letsencrypt
    entrypoint: /bin/sh -c "curl -o /etc/traefik/traefik.toml https://raw.githubusercontent.com/ASLObit/Docker/refs/heads/main/traefik/traefik.toml && traefik"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.tudominio.local`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"

networks:
  web:
    external: true
