version: '3.1'

services:
  web:
    image: odoo:18.0
    container_name: remates-panama-web
    depends_on:
      - db
    ports:
      - "8070:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_web_data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons

  db:
    image: postgres:13
    container_name: remates-panama-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - odoo_remates_panama_remates-panama-db-data:/var/lib/postgresql/data

volumes:
  odoo_web_data:
  odoo_remates_panama_remates-panama-db-data:
    external: true
