version: '3.1'

services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8070:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    volumes:
      - odoo_remates_panama_remates-panama-web-data:/var/lib/odoo
    container_name: remates-panama-web

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo_remates_panama_remates-panama-db-data:/var/lib/postgresql/data
    container_name: remates-panama-db

volumes:
  odoo_remates_panama_remates-panama-web-data:
    external: true
  odoo_remates_panama_remates-panama-db-data:
    external: true
