version: '3.9'

services:
  web:
    image: odoo:18.0
    depends_on:
      - db
    ports:
      - "8071:8069"
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - ADDONS_PATH=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
    volumes:
      - rematespanamastg-web-data:/var/lib/odoo
      - ./rematespanamastg-config:/etc/odoo:rw
      - ./rematespanamastg-addons:/mnt/extra-addons:rw
    container_name: rematespanamastg-web

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - rematespanamastg-db-data:/var/lib/postgresql/data
    container_name: rematespanamastg-db

volumes:
  rematespanamastg-web-data:
  rematespanamastg-db-data: