version: '3'

services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflare
    command: tunnel --no-autoupdate run --token eyJhIjoiMTE5ZWE4NTY4YjZhYjYyNjRmYmZmMWQzYjBlYmFlZGMiLCJ0IjoiMjAyMDJkYTUtYzlkNi00MWMyLWFlMTUtYzkwMjQxNDRhODQ3IiwicyI6Ik5ERXlNV0prTW1JdE16RmxNaTAwWm1ReUxXSTVaREl0TmpoaE5EUTRaVEJrT0daaiJ9
    volumes:
      - /etc/cloudflared:/etc/cloudflared
    restart: always
    network_mode: host
